/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipIdRouteImport } from './routes/scholarship/$id'
import { Route as ApiRetrieveRouteImport } from './routes/api/retrieve'
import { Route as ApiRerankRouteImport } from './routes/api/rerank'
import { Route as ApiPersonalityRouteImport } from './routes/api/personality'
import { Route as ApiMatchRouteImport } from './routes/api/match'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiDbHealthRouteImport } from './routes/api/db-health'
import { Route as ApiClaudeHealthRouteImport } from './routes/api/claude-health'
import { Route as AdminDebugRouteImport } from './routes/admin/debug'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipIdRoute = ScholarshipIdRouteImport.update({
  id: '/scholarship/$id',
  path: '/scholarship/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRetrieveRoute = ApiRetrieveRouteImport.update({
  id: '/api/retrieve',
  path: '/api/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRerankRoute = ApiRerankRouteImport.update({
  id: '/api/rerank',
  path: '/api/rerank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersonalityRoute = ApiPersonalityRouteImport.update({
  id: '/api/personality',
  path: '/api/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchRoute = ApiMatchRouteImport.update({
  id: '/api/match',
  path: '/api/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbHealthRoute = ApiDbHealthRouteImport.update({
  id: '/api/db-health',
  path: '/api/db-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeHealthRoute = ApiClaudeHealthRouteImport.update({
  id: '/api/claude-health',
  path: '/api/claude-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDebugRoute = AdminDebugRouteImport.update({
  id: '/admin/debug',
  path: '/admin/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/admin/debug': typeof AdminDebugRoute
  '/api/claude-health': typeof ApiClaudeHealthRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/match': typeof ApiMatchRoute
  '/api/personality': typeof ApiPersonalityRoute
  '/api/rerank': typeof ApiRerankRoute
  '/api/retrieve': typeof ApiRetrieveRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/admin/debug': typeof AdminDebugRoute
  '/api/claude-health': typeof ApiClaudeHealthRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/match': typeof ApiMatchRoute
  '/api/personality': typeof ApiPersonalityRoute
  '/api/rerank': typeof ApiRerankRoute
  '/api/retrieve': typeof ApiRetrieveRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/admin/debug': typeof AdminDebugRoute
  '/api/claude-health': typeof ApiClaudeHealthRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/match': typeof ApiMatchRoute
  '/api/personality': typeof ApiPersonalityRoute
  '/api/rerank': typeof ApiRerankRoute
  '/api/retrieve': typeof ApiRetrieveRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/admin/debug'
    | '/api/claude-health'
    | '/api/db-health'
    | '/api/draft'
    | '/api/ingest'
    | '/api/match'
    | '/api/personality'
    | '/api/rerank'
    | '/api/retrieve'
    | '/scholarship/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/admin/debug'
    | '/api/claude-health'
    | '/api/db-health'
    | '/api/draft'
    | '/api/ingest'
    | '/api/match'
    | '/api/personality'
    | '/api/rerank'
    | '/api/retrieve'
    | '/scholarship/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/admin/debug'
    | '/api/claude-health'
    | '/api/db-health'
    | '/api/draft'
    | '/api/ingest'
    | '/api/match'
    | '/api/personality'
    | '/api/rerank'
    | '/api/retrieve'
    | '/scholarship/$id'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AdminDebugRoute: typeof AdminDebugRoute
  ApiClaudeHealthRoute: typeof ApiClaudeHealthRoute
  ApiDbHealthRoute: typeof ApiDbHealthRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiMatchRoute: typeof ApiMatchRoute
  ApiPersonalityRoute: typeof ApiPersonalityRoute
  ApiRerankRoute: typeof ApiRerankRoute
  ApiRetrieveRoute: typeof ApiRetrieveRoute
  ScholarshipIdRoute: typeof ScholarshipIdRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship/$id': {
      id: '/scholarship/$id'
      path: '/scholarship/$id'
      fullPath: '/scholarship/$id'
      preLoaderRoute: typeof ScholarshipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retrieve': {
      id: '/api/retrieve'
      path: '/api/retrieve'
      fullPath: '/api/retrieve'
      preLoaderRoute: typeof ApiRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rerank': {
      id: '/api/rerank'
      path: '/api/rerank'
      fullPath: '/api/rerank'
      preLoaderRoute: typeof ApiRerankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/personality': {
      id: '/api/personality'
      path: '/api/personality'
      fullPath: '/api/personality'
      preLoaderRoute: typeof ApiPersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match': {
      id: '/api/match'
      path: '/api/match'
      fullPath: '/api/match'
      preLoaderRoute: typeof ApiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db-health': {
      id: '/api/db-health'
      path: '/api/db-health'
      fullPath: '/api/db-health'
      preLoaderRoute: typeof ApiDbHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude-health': {
      id: '/api/claude-health'
      path: '/api/claude-health'
      fullPath: '/api/claude-health'
      preLoaderRoute: typeof ApiClaudeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/debug': {
      id: '/admin/debug'
      path: '/admin/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof AdminDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AdminDebugRoute: AdminDebugRoute,
  ApiClaudeHealthRoute: ApiClaudeHealthRoute,
  ApiDbHealthRoute: ApiDbHealthRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiMatchRoute: ApiMatchRoute,
  ApiPersonalityRoute: ApiPersonalityRoute,
  ApiRerankRoute: ApiRerankRoute,
  ApiRetrieveRoute: ApiRetrieveRoute,
  ScholarshipIdRoute: ScholarshipIdRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
