/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipIdRouteImport } from './routes/scholarship/$id'
import { Route as EssayIdRouteImport } from './routes/essay/$id'
import { Route as ApiRubricRouteImport } from './routes/api/rubric'
import { Route as ApiReviseRouteImport } from './routes/api/revise'
import { Route as ApiRetrieveRouteImport } from './routes/api/retrieve'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiRerankRouteImport } from './routes/api/rerank'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiPersonalityRouteImport } from './routes/api/personality'
import { Route as ApiMatchRouteImport } from './routes/api/match'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiGradeEssayRouteImport } from './routes/api/grade-essay'
import { Route as ApiExplainFitRouteImport } from './routes/api/explain-fit'
import { Route as ApiDraftsRouteImport } from './routes/api/drafts'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiDbHealthRouteImport } from './routes/api/db-health'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiClaudeHealthRouteImport } from './routes/api/claude-health'
import { Route as AdminDebugRouteImport } from './routes/admin/debug'
import { Route as ApiScholarshipIdRouteImport } from './routes/api/scholarship/$id'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminTelemetryRouteImport } from './routes/api/admin/telemetry'
import { Route as ApiAdminStudentsRouteImport } from './routes/api/admin/students'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipIdRoute = ScholarshipIdRouteImport.update({
  id: '/scholarship/$id',
  path: '/scholarship/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayIdRoute = EssayIdRouteImport.update({
  id: '/essay/$id',
  path: '/essay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRubricRoute = ApiRubricRouteImport.update({
  id: '/api/rubric',
  path: '/api/rubric',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviseRoute = ApiReviseRouteImport.update({
  id: '/api/revise',
  path: '/api/revise',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRetrieveRoute = ApiRetrieveRouteImport.update({
  id: '/api/retrieve',
  path: '/api/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRerankRoute = ApiRerankRouteImport.update({
  id: '/api/rerank',
  path: '/api/rerank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersonalityRoute = ApiPersonalityRouteImport.update({
  id: '/api/personality',
  path: '/api/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchRoute = ApiMatchRouteImport.update({
  id: '/api/match',
  path: '/api/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGradeEssayRoute = ApiGradeEssayRouteImport.update({
  id: '/api/grade-essay',
  path: '/api/grade-essay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainFitRoute = ApiExplainFitRouteImport.update({
  id: '/api/explain-fit',
  path: '/api/explain-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftsRoute = ApiDraftsRouteImport.update({
  id: '/api/drafts',
  path: '/api/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbHealthRoute = ApiDbHealthRouteImport.update({
  id: '/api/db-health',
  path: '/api/db-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeHealthRoute = ApiClaudeHealthRouteImport.update({
  id: '/api/claude-health',
  path: '/api/claude-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDebugRoute = AdminDebugRouteImport.update({
  id: '/admin/debug',
  path: '/admin/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScholarshipIdRoute = ApiScholarshipIdRouteImport.update({
  id: '/api/scholarship/$id',
  path: '/api/scholarship/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTelemetryRoute = ApiAdminTelemetryRouteImport.update({
  id: '/api/admin/telemetry',
  path: '/api/admin/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStudentsRoute = ApiAdminStudentsRouteImport.update({
  id: '/api/admin/students',
  path: '/api/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/admin/debug': typeof AdminDebugRoute
  '/api/claude-health': typeof ApiClaudeHealthRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/drafts': typeof ApiDraftsRoute
  '/api/explain-fit': typeof ApiExplainFitRoute
  '/api/grade-essay': typeof ApiGradeEssayRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/match': typeof ApiMatchRoute
  '/api/personality': typeof ApiPersonalityRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rerank': typeof ApiRerankRoute
  '/api/research': typeof ApiResearchRoute
  '/api/retrieve': typeof ApiRetrieveRoute
  '/api/revise': typeof ApiReviseRoute
  '/api/rubric': typeof ApiRubricRoute
  '/essay/$id': typeof EssayIdRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/admin/telemetry': typeof ApiAdminTelemetryRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/scholarship/$id': typeof ApiScholarshipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/admin/debug': typeof AdminDebugRoute
  '/api/claude-health': typeof ApiClaudeHealthRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/drafts': typeof ApiDraftsRoute
  '/api/explain-fit': typeof ApiExplainFitRoute
  '/api/grade-essay': typeof ApiGradeEssayRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/match': typeof ApiMatchRoute
  '/api/personality': typeof ApiPersonalityRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rerank': typeof ApiRerankRoute
  '/api/research': typeof ApiResearchRoute
  '/api/retrieve': typeof ApiRetrieveRoute
  '/api/revise': typeof ApiReviseRoute
  '/api/rubric': typeof ApiRubricRoute
  '/essay/$id': typeof EssayIdRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/admin/telemetry': typeof ApiAdminTelemetryRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/scholarship/$id': typeof ApiScholarshipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/admin/debug': typeof AdminDebugRoute
  '/api/claude-health': typeof ApiClaudeHealthRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/drafts': typeof ApiDraftsRoute
  '/api/explain-fit': typeof ApiExplainFitRoute
  '/api/grade-essay': typeof ApiGradeEssayRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/match': typeof ApiMatchRoute
  '/api/personality': typeof ApiPersonalityRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/rerank': typeof ApiRerankRoute
  '/api/research': typeof ApiResearchRoute
  '/api/retrieve': typeof ApiRetrieveRoute
  '/api/revise': typeof ApiReviseRoute
  '/api/rubric': typeof ApiRubricRoute
  '/essay/$id': typeof EssayIdRoute
  '/scholarship/$id': typeof ScholarshipIdRoute
  '/api/admin/students': typeof ApiAdminStudentsRoute
  '/api/admin/telemetry': typeof ApiAdminTelemetryRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/scholarship/$id': typeof ApiScholarshipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom'
    | '/dashboard'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/admin/debug'
    | '/api/claude-health'
    | '/api/dashboard'
    | '/api/db-health'
    | '/api/draft'
    | '/api/drafts'
    | '/api/explain-fit'
    | '/api/grade-essay'
    | '/api/ingest'
    | '/api/match'
    | '/api/personality'
    | '/api/plan'
    | '/api/profile'
    | '/api/rerank'
    | '/api/research'
    | '/api/retrieve'
    | '/api/revise'
    | '/api/rubric'
    | '/essay/$id'
    | '/scholarship/$id'
    | '/api/admin/students'
    | '/api/admin/telemetry'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/scholarship/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom'
    | '/dashboard'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/admin/debug'
    | '/api/claude-health'
    | '/api/dashboard'
    | '/api/db-health'
    | '/api/draft'
    | '/api/drafts'
    | '/api/explain-fit'
    | '/api/grade-essay'
    | '/api/ingest'
    | '/api/match'
    | '/api/personality'
    | '/api/plan'
    | '/api/profile'
    | '/api/rerank'
    | '/api/research'
    | '/api/retrieve'
    | '/api/revise'
    | '/api/rubric'
    | '/essay/$id'
    | '/scholarship/$id'
    | '/api/admin/students'
    | '/api/admin/telemetry'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/scholarship/$id'
  id:
    | '__root__'
    | '/'
    | '/custom'
    | '/dashboard'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/admin/debug'
    | '/api/claude-health'
    | '/api/dashboard'
    | '/api/db-health'
    | '/api/draft'
    | '/api/drafts'
    | '/api/explain-fit'
    | '/api/grade-essay'
    | '/api/ingest'
    | '/api/match'
    | '/api/personality'
    | '/api/plan'
    | '/api/profile'
    | '/api/rerank'
    | '/api/research'
    | '/api/retrieve'
    | '/api/revise'
    | '/api/rubric'
    | '/essay/$id'
    | '/scholarship/$id'
    | '/api/admin/students'
    | '/api/admin/telemetry'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/scholarship/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomRoute: typeof CustomRoute
  DashboardRoute: typeof DashboardRoute
  MatchesRoute: typeof MatchesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  AdminDebugRoute: typeof AdminDebugRoute
  ApiClaudeHealthRoute: typeof ApiClaudeHealthRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiDbHealthRoute: typeof ApiDbHealthRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiDraftsRoute: typeof ApiDraftsRoute
  ApiExplainFitRoute: typeof ApiExplainFitRoute
  ApiGradeEssayRoute: typeof ApiGradeEssayRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiMatchRoute: typeof ApiMatchRoute
  ApiPersonalityRoute: typeof ApiPersonalityRoute
  ApiPlanRoute: typeof ApiPlanRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiRerankRoute: typeof ApiRerankRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiRetrieveRoute: typeof ApiRetrieveRoute
  ApiReviseRoute: typeof ApiReviseRoute
  ApiRubricRoute: typeof ApiRubricRoute
  EssayIdRoute: typeof EssayIdRoute
  ScholarshipIdRoute: typeof ScholarshipIdRoute
  ApiAdminStudentsRoute: typeof ApiAdminStudentsRoute
  ApiAdminTelemetryRoute: typeof ApiAdminTelemetryRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiScholarshipIdRoute: typeof ApiScholarshipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship/$id': {
      id: '/scholarship/$id'
      path: '/scholarship/$id'
      fullPath: '/scholarship/$id'
      preLoaderRoute: typeof ScholarshipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay/$id': {
      id: '/essay/$id'
      path: '/essay/$id'
      fullPath: '/essay/$id'
      preLoaderRoute: typeof EssayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rubric': {
      id: '/api/rubric'
      path: '/api/rubric'
      fullPath: '/api/rubric'
      preLoaderRoute: typeof ApiRubricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revise': {
      id: '/api/revise'
      path: '/api/revise'
      fullPath: '/api/revise'
      preLoaderRoute: typeof ApiReviseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retrieve': {
      id: '/api/retrieve'
      path: '/api/retrieve'
      fullPath: '/api/retrieve'
      preLoaderRoute: typeof ApiRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rerank': {
      id: '/api/rerank'
      path: '/api/rerank'
      fullPath: '/api/rerank'
      preLoaderRoute: typeof ApiRerankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/personality': {
      id: '/api/personality'
      path: '/api/personality'
      fullPath: '/api/personality'
      preLoaderRoute: typeof ApiPersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match': {
      id: '/api/match'
      path: '/api/match'
      fullPath: '/api/match'
      preLoaderRoute: typeof ApiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grade-essay': {
      id: '/api/grade-essay'
      path: '/api/grade-essay'
      fullPath: '/api/grade-essay'
      preLoaderRoute: typeof ApiGradeEssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain-fit': {
      id: '/api/explain-fit'
      path: '/api/explain-fit'
      fullPath: '/api/explain-fit'
      preLoaderRoute: typeof ApiExplainFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts': {
      id: '/api/drafts'
      path: '/api/drafts'
      fullPath: '/api/drafts'
      preLoaderRoute: typeof ApiDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db-health': {
      id: '/api/db-health'
      path: '/api/db-health'
      fullPath: '/api/db-health'
      preLoaderRoute: typeof ApiDbHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude-health': {
      id: '/api/claude-health'
      path: '/api/claude-health'
      fullPath: '/api/claude-health'
      preLoaderRoute: typeof ApiClaudeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/debug': {
      id: '/admin/debug'
      path: '/admin/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof AdminDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scholarship/$id': {
      id: '/api/scholarship/$id'
      path: '/api/scholarship/$id'
      fullPath: '/api/scholarship/$id'
      preLoaderRoute: typeof ApiScholarshipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/telemetry': {
      id: '/api/admin/telemetry'
      path: '/api/admin/telemetry'
      fullPath: '/api/admin/telemetry'
      preLoaderRoute: typeof ApiAdminTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/students': {
      id: '/api/admin/students'
      path: '/api/admin/students'
      fullPath: '/api/admin/students'
      preLoaderRoute: typeof ApiAdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomRoute: CustomRoute,
  DashboardRoute: DashboardRoute,
  MatchesRoute: MatchesRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  AdminDebugRoute: AdminDebugRoute,
  ApiClaudeHealthRoute: ApiClaudeHealthRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiDbHealthRoute: ApiDbHealthRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiDraftsRoute: ApiDraftsRoute,
  ApiExplainFitRoute: ApiExplainFitRoute,
  ApiGradeEssayRoute: ApiGradeEssayRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiMatchRoute: ApiMatchRoute,
  ApiPersonalityRoute: ApiPersonalityRoute,
  ApiPlanRoute: ApiPlanRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiRerankRoute: ApiRerankRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiRetrieveRoute: ApiRetrieveRoute,
  ApiReviseRoute: ApiReviseRoute,
  ApiRubricRoute: ApiRubricRoute,
  EssayIdRoute: EssayIdRoute,
  ScholarshipIdRoute: ScholarshipIdRoute,
  ApiAdminStudentsRoute: ApiAdminStudentsRoute,
  ApiAdminTelemetryRoute: ApiAdminTelemetryRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiScholarshipIdRoute: ApiScholarshipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
